# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c35a3f53fafcdf45f1cd07a79ec0231eb6ed99aa7dcaa934658b305f4d9f6f90226c57110be62bf7a8bf993ef293d1e0a3e9913acbdc32662928648daa8ca7c

test:
  secret_key_base: addcc1e773749400754f04cb325040b9a11631625ad784971de27fc766655d0e41ee6abbe710ddc53ff00d9b68acb732328513e6f619628f71d5a40569d49865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
